#!/bin/sh
# Usage: exifdiff.sh path/file1.ext path/file2.ext parameters
# eg:    exifdiff.sh dsc_7811.nef ./jpegs/dsc_7811.jpg
# eg:    exifdiff.sh dsc_7811.nef ./jpegs/dsc_7811.jpg -a -G1 -datetimeoriginal

B1=$(basename "${1}")
B2=$(basename "${2}")

exiftool -a -G1 -s "${@}" -w! /tmp/%d%f.%e.txt \
	&& diff -y -W $(tput cols) <(sort /tmp/"${1}".txt) <(sort /tmp/"${2}".txt)
